<script lang="ts">
	import { goto } from '$app/navigation';
	import { Altron } from '@altron/altron';
	import type { Altron as altronType } from '@altron/altron';
	import { onMount } from 'svelte';
	import CloseIcon from '$lib/components/icons/closeIcon.svelte';
	import Code from '$lib/components/handlers/code.svelte';
	let editor: altronType = null;

	onMount(() => {
		editor.setData([
			{
				name: 'header',
				id: '1',
				data: {
					level: 1,
					text: 'Sha1 hash function'
				}
			},
			{
				name: 'space',
				id: '2',
				data: { size: 10 }
			},
			{
				name: 'paragraph',
				id: '3',
				data: {
					text: 'SHA-1 or Secure Hash Algorithm 1 is a cryptographic algorithm which takes an input and produces a 160-bit (20-byte) hash value. This hash value is known as a message digest. This message digest is usually then rendered as a hexadecimal number which is 40 digits long. It is a U.S. Federal Information Processing Standard and was designed by the United States National Security Agency. SHA-1 is now considered insecure since 2005. Major tech giants browsers like Microsoft, Google, Apple and Mozilla have stopped accepting SHA-1 SSL certificates by 2017.'
				}
			},
			{
				name: 'header',
				id: '5',
				data: {
					level: 3,
					text: 'Code example in java'
				}
			},
			{
				id: '7',
				name: 'code',
				data: {
					lang: 'java',
					text: `// Java program to calculate SHA-1 hash value

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class GFG {
	public static String encryptThisString(String input)
	{
		try {
			MessageDigest md = MessageDigest.getInstance("SHA-1");			
			byte[] messageDigest = md.digest(input.getBytes());
			BigInteger no = new BigInteger(1, messageDigest);
			String hashtext = no.toString(16);
			while (hashtext.length() < 32) {
				hashtext = "0" + hashtext;
			}
			return hashtext;
		}
		catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		}
	}
	public static void main(String args[]) throws NoSuchAlgorithmException
	{
		System.out.println("HashCode Generated by SHA-1 for: ");
		String s1 = "GeeksForGeeks";
		System.out.println("\n" + s1 + " : " + encryptThisString(s1));
		String s2 = "hello world";
		System.out.println("\n" + s2 + " : " + encryptThisString(s2));
	}
}
`
				}
			},
			{
				name: 'space',
				id: '2',
				data: { size: 10 }
			},
			{
				id: '12',
				name: 'header',
				data: {
					text: 'ComputerPhile video about sha1',
					level: 3
				}
			},
			{
				id: '9',
				name: 'embed',
				data: {
					src: 'https://www.youtube.com/embed/DMtFhACPnTY'
				}
			},
			{
				id: '14',
				name: 'header',
				data: {
					level: 3,
					text: 'Sha1 disadventages'
				}
			},
			{
				id: '16',
				name: 'list',
				data: {
					type: 'unordered',
					items: ['Collision Vulnerability', 'Practical Exploitation', 'Deprecation by Standards']
				}
			},
			{
				id: '19',
				name: 'header',
				data: {
					level: 3,
					text: 'When can we use sha1?'
				}
			},
			{
				id: '90',
				name: 'checklist',
				data: {
					items: [
						{
							value: 'Checksums',
							checked: true
						},
						{
							value: 'hashing passwords',
							checked: false
						},
						{
							value: 'Signing digital certificates or documents.',
							checked: false
						}
					]
				}
			}
		]);
	});
</script>

<div class="example">
	<header>
		<!-- svelte-ignore a11y-click-events-have-key-events -->
		<!-- svelte-ignore a11y-no-static-element-interactions -->
		<span
			on:click={() => {
				goto('/');
			}}><CloseIcon /></span
		>
	</header>
	<section class="editor">
		<Altron
			primaryColor={'#3164ff'}
			secondaryColor={'#14c489'}
			bgColor={'#ffffff'}
			textColor={'#121212'}
			blocksGap={'10px'}
			customCode={Code}
			viewMode={true}
			bind:this={editor}
			headerFont="'Montserrat', sans-serif"
			bodyFont="'Source Sans 3', sans-serif"
		/>
	</section>
</div>

<style>
	.example {
		width: 95vw;
		height: 100vh;
		display: flex;
		flex-direction: column;
		align-items: center;
		padding-top: 20px;
		padding-left: 20px;
		gap: 40px;
	}
	header {
		width: 100%;
		display: flex;
	}
	header span {
		width: 42px;
		height: 42px;
		border-radius: 50%;
		border: 2px solid var(--primary800);
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
	}
	header span :global(path) {
		fill: var(--primary800);
	}
	header span:hover {
		background-color: var(--primary400);
	}

	.editor {
		width: 60%;
	}
	@media screen and (width < 768px) {
		.editor {
			width: 100%;
		}
	}
</style>
